import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/components/Provider'
import IntlGlobalProvider from '@/components/IntlGlobalProvider'


const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <IntlGlobalProvider>
          {children}
        </IntlGlobalProvider>
          
        
        </Providers>
      </body>
    </html>
  )
}
